### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by lucapinello** [masato-ogishi/Repitope#11]
Hello nice tool,

I tried to install on the latest version of R but I got the following error:

> devtools::install_github("masato-ogishi/plotUtility")
Skipping install of 'plotUtility' from a github remote, the SHA1 (5afe2428) has not changed since last install.
  Use `force = TRUE` to force installation
> devtools::install_github("masato-ogishi/Repitope")
Downloading GitHub repo masato-ogishi/Repitope@master
Skipping 3 packages not available: Biostrings, msa, S4Vectors
Installing 87 packages: BBmisc, Biostrings, car, caret, cvAUC, data.table, DescTools, doParallel, doSNOW, extraTrees, foreach, fst, ggpubr, ggsci, gridExtra, igraph, matrixStats, mlr, msa, pbapply, Peptides, precrec, pROC, psych, randomForestSRC, rlecuyer, S4Vectors, seqinr, snow, stringdist, survminer, VennDiagram, zoo, checkmate, carData, abind, pbkrtest, quantreg, maptools, rio, lme4, ModelMetrics, recipes, ROCR, mvtnorm, expm, iterators, rJava, ggrepel, cowplot, ggsignif, polynom, ParamHelpers, parallelMap, XML, mnormt, ade4, segmented, maxstat, survMisc, futile.logger, minqa, nloptr, RcppEigen, SparseM, MatrixModels, sp, openxlsx, gower, ipred, timeDate, prodlim, lava, numDeriv, SQUAREM, gplots, gtools, gdata, caTools, bitops, fastmatch, exactRankTests, KMsurv, km.ci, lambda.r, futile.options, formatR
Error: Failed to install 'Repitope' from GitHub:
  (converted from warning) packages ‘Biostrings’, ‘msa’, ‘S4Vectors’ are not available (for R version 3.6.1)

Can you please take a look?

Thanks,

Luca

**Comment by masato-ogishi** [comment]
Thanks for trying Repitope. The following script should work. 

devtools::install_github("masato-ogishi/plotUtility", force=T)
if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
BiocManager::install("Biostrings")
BiocManager::install("msa")
BiocManager::install("S4Vectors")
devtools::install_github("masato-ogishi/Repitope", force=T)

Enjoy!

Masato

**Comment by lucapinello** [comment]
Thanks for the reply. I have now another error related to java.

 installing *source* package ‘Repitope’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Unable to find any JVMs matching version "(null)".
No Java runtime present, try --request to install.
Warning in system("/usr/libexec/java_home", intern = TRUE) :
  running command '/usr/libexec/java_home' had status 1
Error: .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: /Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home/lib/server/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/library/rJava/libs/rJava.so
  Reason: image not found
Execution halted
ERROR: lazy loading failed for package ‘Repitope’
* removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Repitope’
Error: Failed to install 'Repitope' from GitHub:
  (converted from warning) installation of package ‘/var/folders/18/qxw249fn24x9_flh9kl5m0f40000gn/T//RtmpI1K4hJ/file73516e4b9978/Repitope_3.1.1.tar.gz’ had non-zero exit status
> 

Do you know how to fix this? I have installed the lastest version of Java from here: https://www.java.com/en/download/mac_download.jsp

I am using a Mac.

Thanks again,

Luca

**Comment by masato-ogishi** [comment]
Hi Luca,

I have encountered the same problem before, and as far as I remember this
link helped me. This is a problem of JAVA and Mac, which is absolutely
beyond me actually...
https://zhiyzuo.github.io/installation-rJava/

Hope this helps!

Best,
Masato


2019年10月14日(月) 14:28 Luca Pinello <notifications@github.com>:

**Comment by lucapinello** [comment]
Thanks! I will check out this link.
