### ISSUE TITLE
Epitope Import issue

### ISSUE THREAD

**Issue by elyawy** [masato-ogishi/Repitope#12]
Hi, 
I have some issues with the Epitope import method, it does not import 31,693 epitopes only 198.
what could be the issue? 
![Screenshot_2020-01-01_14-32-15](https://user-images.githubusercontent.com/779951/71641381-dc90f400-2ca3-11ea-989e-efa614617307.png)

**Comment by masato-ogishi** [comment]
I forgot to include "peptideLengthSet" variable during the sequence filtering step in the Epitope_Import function.
Bug fixed. 
Thanks for reporting.
