### ISSUE TITLE
Fatal Error Loading Repitope

### ISSUE THREAD

**Issue by paulrbuckley** [masato-ogishi/Repitope#13]
Hi,

Over the last couple of days I have been working with Repitope. I have had a few errors i am trying to work through, but as of today, i cannot even load the package anymore. My 'rJava' is working as expected, however when i run 

`library(Repitope)` 

inside RStudio, i am told that the r session must be terminated due to a fatal error. If i run in terminal, i am given the following:

_"R(1268,0x10926fdc0) malloc: *** error for object 0x7fff93978890: pointer being freed was not allocated
R(1268,0x10926fdc0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6"_

i am wondering if you had any thoughts on what this could mean?

best

Paul

**Comment by masato-ogishi** [comment]
To me it looks like a hardware problem. I recommend you reinstalling R and RStudio. Also try different libraries to see if this is package-dependent or -independent.

Good luck,
Masato
