### ISSUE TITLE
Correlation matrix has missing values

### ISSUE THREAD

**Issue by paulrbuckley** [masato-ogishi/Repitope#14]
Hi,

After the issue the other day, i am running REpitope on a different machine and most of the process works well. I am struggling with feature selection however. Even when using the supplied code on github, i receive the following error after the 'FeaturesMinimumFeatures' function: 

_Error in, task 1 failed, the correlation matrix has some missing values_. I am not sure what is causing this as I have checked the input data, and this also occurs when using the MHCI_Human data. The code i am using is below. You'll see that I have subset the data to the first 100 rows while I am troubleshooting, to save some time in processing.

Do you have any ideas on what might be wrong? 

Best

P

`fragLibDT <- CPP_FragmentLibrary(TCRSet_Public, fragLenSet=3:11, maxFragDepth=100000, seedSet=1:1)
fst::write_fst(fragLibDT, "FragmentLibrary.fst", compress=0)
 
MHCI_Human=MHCI_Human[1:100]
 
# I have to run the below function twice as the first time, i get the 'argument x must be a vector' error.
featureDFList_MHCI <- Features(
  peptideSet=unique(c(MHCI_Human$Peptide)),
  fragLib="FragmentLibrary.fst",
  aaIndexIDSet="all",
  fragLenSet=3:8,
  fragDepth=10000,
  fragLibType="Weighted",
  seedSet=1:1,                                   ## must be the same random seeds used for preparing the fragment library
  coreN=parallel::detectCores(logical=F),        ## parallelization
  tmpDir="temp"   ## where intermediate files are stored
)
 
saveFeatureDFList(featureDFList_MHCI, "FeatureDF_")
 
# Code fails on below function
featureDF_MHCI <- fst::read_fst("FeatureDF_Weighted.10000.fst", as.data.table=T)
minFeatureSet_MHCI_Human <- Features_MinimumFeatures(
  featureDFList=list(featureDF_MHCI[Peptide%in%MHCI_Human$Peptide,]),
  metadataDF=MHCI_Human[,.(Peptide,Immunogenicity)][,Cluster:=.I],
  seedSet=1:1,
  corThreshold=0.75,
  featureNSet=100,
  criteria="intersect",
 returnImpDFList=T
)
  

)`

**Comment by masato-ogishi** [comment]
It seems like an update of the underlying caret function was the cause of the trouble. I updated the relevant workflow. Please try reinstalling the package.

**Comment by paulrbuckley** [comment]
Hi,

Thanks for updating thatn so promptly, the previous code now runs perfectly. Now, i run into a data table error when running Immunogenicity_Score function. From what i can tell this error occurs when running the Immunogenicity_TrainModels function.  

_Error in `[.data.table`(dt, , c("Peptide", "Immunogenicity", featureSet),  :
  When with=FALSE, j-argument should be of type logical/character/integer indicating the columns to select._

This is when running the code; 

`scoreDF_MHCI_Human <- Immunogenicity_Score(
   featureDF=featureDF_MHCI[Peptide%in%MHCI_Human$Peptide,],
   metadataDF=MHCI_Human[,.(Peptide, Immunogenicity)],
   featureSet=minFeatureSet_MHCI_Human,
   seedSet=1:1
 )`

Let me know if i'm running something incorrectly but as far as i can tell the code im running is accurate.

cheers

P

**Comment by masato-ogishi** [comment]
In your case, minFeatureSet_MHCI_Human is a list object, I believe, because you set returnImpDFList=T. In this case, the right code is:
scoreDF_MHCI_Human <- Immunogenicity_Score( featureDF=featureDF_MHCI[Peptide%in%MHCI_Human$Peptide,], metadataDF=MHCI_Human[,.(Peptide, Immunogenicity)], featureSet=minFeatureSet_MHCI_Human$"MinimumFeatureSet", seedSet=1:1 )
If you set returnImpDFList=F, minFeatureSet_MHCI_Human would become a simple character vector. 
I'll add an input check command internally. Thanks for trying out.
P.S. Alternatively, the package already provides "MHCI_Human_MinimumFeatureSet" object for use.

**Comment by paulrbuckley** [comment]
Thanks a lot, pipeline works fully now

cheers

P

**Comment by Hayfabm** [comment]
Hi @masato-ogishi, 

I have another issue regarding `Features_MinimumFeatures`:

```
# Feature selection [MHC-I]
featureDF_MHCI <- fst::read_fst("./Path/To/Your/Directory/MHCI/FeatureDF_Weighted.10000.fst", as.data.table=T)
minFeatureSet_MHCI_Human <- Features_MinimumFeatures(
  featureDFList=list(featureDF_MHCI[Peptide%in%MHCI_Human$Peptide,]),
  metadataDF=MHCI_Human[,.(Peptide,Immunogenicity)][,Cluster:=.I],
  seedSet=1:5,
  corThreshold=0.75,
  featureNSet=100,
  criteria="intersect",
  returnImpDFList=T
)

```
Here's the following output: 
```
Error in FUN(X[[i]], ...) : 
  Assertion on 'unlist(method)' failed: Must be a subset of {'anova.test','auc','carscore','cforest.importance','chi.squared','FSelector_chi.squared','FSelector_gain.ratio','FSelector_information.gain','FSelector_oneR','FSelector_relief','FSelector_symmetrical.uncertainty','FSelectorRcpp_gain.ratio','FSelectorRcpp_information.gain','FSelectorRcpp_relief','FSelectorRcpp_symmetrical.uncertainty','gain.ratio','information.gain','kruskal.test','linear.correlation','mrmr','oneR','party_cforest.importance','permutation.importance','praznik_CMIM','praznik_DISR','praznik_JMI','praznik_JMIM','praznik_MIM','praznik_MRMR','praznik_NJMIM','randomForest_importance','randomForest.importance','ranger_impurity','ranger_permutation','ranger.impurity','ranger.permutation','rank.correlation','relief','symmetrical.uncertainty','univariate','univariate.model.score','variance','E-Borda','E-max','E-mean','E-median','E-min'}, but has additional elements {'randomForestSRC_importance'}.
```
Do you have any ideas on what could be causing the problem?
