### ISSUE TITLE
Issue if there's no immunogenicity conflicts

### ISSUE THREAD

**Issue by paulrbuckley** [masato-ogishi/Repitope#15]
Hi,

If you use the function Epitope_Import, and there are no conflicts in your data for peptide immunogenicity, you receive the error 'Error in cont[[2]]: subscript out of bounds'. 

I've been getting around this by creating an artificial conflict for a peptide, which resolves the issue. Thought it worth lettinng you know.

cheers

Paul

**Comment by masato-ogishi** [comment]
Thanks for letting me know. That's definitely a bug. Fixed. 
Best, 
Masato
