### ISSUE TITLE
Epitope Prediction without known annotation

### ISSUE THREAD

**Issue by paulrbuckley** [masato-ogishi/Repitope#16]
Hi Masato,

Sorry if i'm missing something here. In the past i have used REpitope when I know the immunogenicity annotation, and this has worked well to generate immunogenicity probabilities. I am wondering whether it is possible to generate immunogenicity probabilities, when the immunogenicity isn't known/provided to REpitope? I've tried in the past and remember getting an error message so left it alone.

cheers

Paul

**Comment by paulrbuckley** [comment]
Pretty sure this can be closed. Assuming this is done through a respective combination of feature computation, 'Immunogenicity_TrainModels' and 'ImmunogenicityPredict' for the external features.

**Comment by masato-ogishi** [comment]
Yes, this can be done using the combination of Immunogenicity_TrainModels and Immunogenicity_Predict. Note that the prediction should be performed using the model trained without the peptides to be predicted. In case your peptides of interest do not have immunogenicity annotation, it is fine. In case your peptides of interest do have annotation, please be advised not to use them during the model training phase. This would cause overfitting. The Immunogenicity_Predict function also gives you a warning if it detects identical peptides used in the model training phase and the prediction phase.
