### ISSUE TITLE
Data question: HLA Allele 

### ISSUE THREAD

**Issue by paulrbuckley** [masato-ogishi/Repitope#17]
Hi,

I justr wanted to confirm in the MHCI_Human dataset, when a peptide's HLA allele is classified as 'A|B', e.g _'HLA-A*03:01|HLA-A*11:01|HLA-A*33:01|HLA-A*33:03|HLA-A*68:01'_ - i assume that this mean that the peptide in question has been show to be immunogenic in the context of each of these alleles?

**Comment by masato-ogishi** [comment]
Yes, the data is mainly compiled from IEDB, in which the HLA alleles of the cells tested are also provided.
