### ISSUE TITLE
Task 120 failed / featureDFList_MHCI

### ISSUE THREAD

**Issue by FabriceRenaud** [masato-ogishi/Repitope#3]
Hi Masato,

Thank you for providing your code! 

I want to run your code with a small dataset of my own containing 459 unique peptides of variable length between 5 and 18 amino acids. 

I create my own data.table(MHCI_Human) with the same colnames as yours. But I'm not using Epitope_Import() to create it. 

When I run the Features function I got the following error right after I the "Peptide descriptor analysis" message.: 

**Error in { : 
  task 120 failed - "Argument 'x' must be a matrix or a vector."**

I believe the error come when peptideDescriptor.FragStat.Single() is called. 

Being a beginner with those kind of code I'm struggling to identify what causes  the error but I have two potential ideas: 
1) I should create my MHCI_Human database by using Epitope_Import() to have the appropriate data structure?
2) Fragment size must be 8-11 or at least >=8mer ?

Do I make an obvious mistake here? 
Thanks in advance,

Fabrice

**Comment by paulrbuckley** [comment]
Having the same issue. Any chance you remember what the solution was?

cheers

P
