### ISSUE TITLE
Questions about the parameter fragDepth

### ISSUE THREAD

**Issue by songofbin** [masato-ogishi/Repitope#4]
Hi Masato,

I have questions about the parameter fragDepth.

1, I think function CPP_FragmentLibrary doesn't have a parameter "maxFragDepth", it should be "fragDepth".

2, I was wondering why fragDepth was setting differently when building fragLibDT and Epitope prioritization?

fragLibDT <- CPP_FragmentLibrary(TCRSet_Public, fragLenSet=3:11, **maxFragDepth=100000,** seedSet=1:5)

res_MHCI <- EpitopePrioritization(
  featureDF=featureDF_MHCI[Peptide%in%MHCI_Human$Peptide,], 
  metadataDF=MHCI_Human[,.(Peptide,Immunogenicity)],
  peptideSet=peptideSet_of_interest,
  fragLib=fragLibDT,
  aaIndexIDSet="all",
  fragLenSet=3:8,
  **fragDepth=10000,**
  fragLibType="Weighted",
  featureSet=MHCI_Human_MinimumFeatureSet,
  seedSet=1:5,
  coreN=parallel::detectCores(logical=F),
  outDir="./Output"  ## Intermediate and final output files will be stored under this directory
)

**Comment by masato-ogishi** [comment]
I originally tested the framework with different fragDepth (100, 1000, 10000, 100000). The parameter maxFragDepth is basically the maximum number of fragments retained in the Fragment Library. By setting this parameter to 100000, I reused the library for subsequent analysis. In other words, maxFragDepth should always be >=fragDepth. I thought fragDepth=10000 was fine, and did subsequent analyses. So you can just set maxFragDepth=10000.
