### ISSUE TITLE
What is the threshold of Repitope results?

### ISSUE THREAD

**Issue by songofbin** [masato-ogishi/Repitope#5]
Hi Masato,

I have got the result file "EpitopePrioritizationSummary.csv" with 3 scores "ImmunogenicityScore, ImmunogenicityScore_Cluster_Average, EscapePotential". I know it had been ranked, but don't know how to do epitope prioritization? What is the threshold for each score?

Thanks.

**Comment by masato-ogishi** [comment]
One idea is to get the optimal cutoff from the ROC curves. 
Here's an example script. The suggested cutoff values are 0.36 and 0.54 for MHC-I and MHC-II, respectively. However, given the large overlap between the positives and negatives, these values are not an absolutely definitive cutoff.

library(Repitope)
library(pROC)

df1 <- merge(MHCI_Human, ScoreDF_MHCI)
roc1 <- roc(Immunogenicity ~ ImmunogenicityScore , data=df1, partial.auc=c(1, .75), partial.auc.focus="sensitivity")
coords(roc=roc1, x="best", input="threshold", best.method="youden", transpose=F)

df2 <- merge(MHCII_Human, ScoreDF_MHCII)
roc2 <- roc(Immunogenicity ~ ImmunogenicityScore , data=df2, partial.auc=c(1, .75), partial.auc.focus="sensitivity")
coords(roc=roc2, x="best", input="threshold", best.method="youden", transpose=F)
