### ISSUE TITLE
File "FragmentLibrary.fst" is wanted

### ISSUE THREAD

**Issue by songofbin** [masato-ogishi/Repitope#6]
I'm wondering if you could offer the FragmentLibrary.fst file you used to build the FeatureDF_MHCI_Weighted.10000.fst file. It seems like I could't get the same ImmunogenicityScore of the 21162 MHCI peptides with the FragmentLibrary.fst file built by myself.

**Comment by masato-ogishi** [comment]
Here's the script to generate the fragment library. 
library(Repitope)
fragLibDT <- CPP_FragmentLibrary(TCRSet_Public, fragLenSet=3:11, maxFragDepth=100000, seedSet=1:5)
fst::write_fst(fragLibDT, "./TCRRepertoire/FragmentLibrary_TCRSet_Public.fst", compress=0)
I'm pretty sure this is reproducible.
