### ISSUE TITLE
Function InSilicoMutagenesis() do not take argument coreN

### ISSUE THREAD

**Issue by SilenWang** [masato-ogishi/Repitope#9]
Hi Masato,
I got a problem when trying to get the final result according to your README on a 40 core computing node, the program will create a lot of processes and eventully failed, even if I set `coreN` manually.
And I found it due to the function `InSilicoMutagenesis()` in `Utility_Sequence.R`, this function will ignore the given `coreN` and use all cores detected.
Hope you can fix this in the future.

Thanks,
Silen

**Comment by SilenWang** [comment]
Hi Masato,
Emmmmm....since it is such a small bug.... I fixed it myself and open a pull request. 

Silen

**Comment by masato-ogishi** [comment]
Thanks and sorry for the late response. I re-wrote the function so now it takes a coreN parameter.
